.s_axi_b_awid      (s_axi_b_awid   [inst]),
.s_axi_b_awaddr    (s_axi_b_awaddr [inst]),
.s_axi_b_awlen     (s_axi_b_awlen  [inst]),
.s_axi_b_awsize    (s_axi_b_awsize [inst]),
.s_axi_b_awburst   (s_axi_b_awburst[inst]),
.s_axi_b_awlock    (s_axi_b_awlock [inst]),
.s_axi_b_awcache   (s_axi_b_awcache[inst]),
.s_axi_b_awprot    (s_axi_b_awprot [inst]),
.s_axi_b_awvalid   (s_axi_b_awvalid[inst]),
.s_axi_b_awready   (s_axi_b_awready[inst]),
.s_axi_b_wdata     (s_axi_b_wdata  [inst]),
.s_axi_b_wstrb     (s_axi_b_wstrb  [inst]),
.s_axi_b_wlast     (s_axi_b_wlast  [inst]),
.s_axi_b_wvalid    (s_axi_b_wvalid [inst]),
.s_axi_b_wready    (s_axi_b_wready [inst]),
.s_axi_b_bid       (s_axi_b_bid    [inst]),
.s_axi_b_bresp     (s_axi_b_bresp  [inst]),
.s_axi_b_bvalid    (s_axi_b_bvalid [inst]),
.s_axi_b_bready    (s_axi_b_bready [inst])
