`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 05/29/2025 02:51:25 PM
// Design Name: 
// Module Name: fp64_mult_tb
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

module fp64_mult_tb;

    // Clock and reset
    logic clk = 0;
    logic rst = 1;
    always #5 clk = ~clk; // 100 MHz clock

    // Cycle counter
    int cycle_counter = 0;
    always_ff @(posedge clk) cycle_counter <= cycle_counter + 1;

    // DUT inputs and outputs
    logic [63:0] a, b;

    // IP core outputs
    logic [63:0] ip_result_bits;
    logic        ip_result_valid;

    // Custom module outputs
    logic [63:0] custom_result_bits;
    logic        custom_valid;

    // Instantiate IP core (generated by Vivado)
    logic s_axis_a_tvalid = 1'b1;
    logic s_axis_b_tvalid = 1'b1;
    logic m_axis_result_tready = 1'b1;

    fp64_mult_ip ip_inst (
        .aclk(clk),
        .s_axis_a_tvalid(s_axis_a_tvalid),
        .s_axis_a_tdata(a),
        .s_axis_b_tvalid(s_axis_b_tvalid),
        .s_axis_b_tdata(b),
        .m_axis_result_tvalid(ip_result_valid),
        .m_axis_result_tdata(ip_result_bits),
        .m_axis_result_tready(m_axis_result_tready)
    );

    // Instantiate custom pipelined multiplier
    fp64_mult custom_inst (
        .clk(clk),
        .rst(rst),
        .a(a),
        .b(b),
        .result(custom_result_bits),
        .valid_out(custom_valid)
    );

    // Real conversion
    function real bits_to_real(input [63:0] b);
        bits_to_real = $bitstoreal(b);
    endfunction

    // Main test sequence
    initial begin
        real ra, rb, expected;
        real ip_result, custom_result;
        int start_cycle, ip_end_cycle, custom_end_cycle;

        // Assert reset for 2 cycles
        rst = 1;
        repeat (2) @(posedge clk);
        rst = 0;

        // Set known IEEE 754 inputs (? and -e)
        a = 64'h400921fb54442d18;   // ? = 3.1415926535
        b = 64'hc005bf0a8b145769;   // -e = -2.7182818284

        // Compute expected result in software
        ra = $bitstoreal(a);
        rb = $bitstoreal(b);
        expected = ra * rb;

        @(posedge clk);
        start_cycle = cycle_counter;

        // Wait for IP result to become valid
        do begin
            @(posedge clk);
        end while (ip_result_valid !== 1'b1 || ip_result_bits == 64'd0);
        
        ip_end_cycle = cycle_counter;
        ip_result = bits_to_real(ip_result_bits);

        // Wait 4 more cycles for custom pipeline to finish
        wait (custom_valid);
        custom_end_cycle = cycle_counter;
        custom_result = bits_to_real(custom_result_bits);

        // Display results
        $display("------ Test Result ------");
        $display("Input A             = %e", ra);
        $display("Input B             = %e", rb);
        $display("Expected            = %e", expected);
        $display("IP Result           = %e", ip_result);
        $display("Custom Result       = %e", custom_result);
        $display("IP Error            = %e", ip_result - expected);
        $display("Custom Error        = %e", custom_result - expected);
        $display("IP Latency          = %0d cycles", ip_end_cycle - start_cycle);
        $display("Custom Latency      = %0d cycles", custom_end_cycle - start_cycle);
        $display("a bits              = %h", a);
        $display("b bits              = %h", b);
        $display("ip_result_bits      = %h", ip_result_bits);
        $display("custom_result_bits  = %h", custom_result_bits);

        $finish;
    end

endmodule

